name: Test Plone 6 documentation

on:
  push:
    branches-ignore:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q -r requirements.txt
          sudo snap install --edge vale

      - name: Run tests with make test
        run: |
          git clone https://github.com/errata-ai/Microsoft.git
          cp –R ./Microsoft ./styles/Microsoft
          make deps
          VALEFILES=$(find -L ./docs/ -type d \( -path "./docs/plone.restapi/lib/*" -o -path "./docs/plone.restapi/performance/*" \) -prune -false -o -type f -name "*.md" -print)
          make vale $VALEFILES
